language: csharp

# whitelist
branches:
  only:
    - master

solution: ErrorCentral.sln
dotnet: 3.1
script:
  - dotnet restore
  - dotnet build -c release
  - dotnet test -c release -l trx -r TestsResults
